[package]
name = "crust"
version = "0.1.0"
edition = "2021"

[dependencies]
# termsize = "0.1"
ratatui = "0.27.0"
crossterm = "0.27.0"
chrono = "0.4.38"
getopts = "0.2.21"
serde = { version = "1.0.204", features = ["derive"] }
toml = "0.8.14"
dirs = "5.0.1"
